### ISSUE TITLE
The site has errors when running on the latest Chrome

### ISSUE THREAD

**Issue by zilongshanren** [IMGROOT2/algo#11]
<img width="652" alt="image" src="https://github.com/IMGROOT2/algo/assets/785541/1541de45-a894-4407-8021-d4d66e47c30a">

**Comment by IMGROOT2** [comment]
When you signed up for Algo on May 9, the website didn't make a user file in the database for you. I've created one manually, so the web app should work correctly now. I switched the database format sometime after May 9, after you first created your account, which may have caused the issue.

Sorry for the inconvenience! Please let me know if anything else happens.
